package com.example.tasksmanager.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDark = Color(0xFFCFBDFE)
val onPrimaryDark = Color(0xFF36275D)
val primaryContainerDark = Color(0xFF4D3D75)
val onPrimaryContainerDark = Color(0xFFE9DDFF)
val secondaryDark = Color(0xFFCFBDFE)
val onSecondaryDark = Color(0xFF36275D)
val secondaryContainerDark = Color(0xFF4D3D75)
val onSecondaryContainerDark = Color(0xFFE9DDFF)
val tertiaryDark = Color(0xFFFFB0C9)
val onTertiaryDark = Color(0xFF541D33)
val tertiaryContainerDark = Color(0xFF6F3349)
val onTertiaryContainerDark = Color(0xFFFFD9E3)
val errorDark = Color(0xFFFFB3AD)
val onErrorDark = Color(0xFF571E1B)
val errorContainerDark = Color(0xFF73332F)
val onErrorContainerDark = Color(0xFFFFDAD7)
val backgroundDark = Color(0xFF141218)
val onBackgroundDark = Color(0xFFE6E0E9)
val surfaceDark = Color(0xFF34313A)
val onSurfaceDark = Color(0xFFE6E0E9)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCAC4CF)
val outlineDark = Color(0xFF948F99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E0E9)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF65558F)
val surfaceDimDark = Color(0xFF141218)
val surfaceBrightDark = Color(0xFF3B383E)
val surfaceContainerLowestDark = Color(0xFF0F0D13)
val surfaceContainerLowDark = Color(0xFF1D1B20)
val surfaceContainerDark = Color(0xFF211F24)
val surfaceContainerHighDark = Color(0xFF2B292F)
val surfaceContainerHighestDark = Color(0xFF36343A)

val primaryDarkMediumContrast = Color(0xFFD3C1FF)
val onPrimaryDarkMediumContrast = Color(0xFF1B0942)
val primaryContainerDarkMediumContrast = Color(0xFF9887C5)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD3C1FF)
val onSecondaryDarkMediumContrast = Color(0xFF1B0942)
val secondaryContainerDarkMediumContrast = Color(0xFF9887C5)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFB7CD)
val onTertiaryDarkMediumContrast = Color(0xFF330218)
val tertiaryContainerDarkMediumContrast = Color(0xFFC57B93)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFB9B3)
val onErrorDarkMediumContrast = Color(0xFF330405)
val errorContainerDarkMediumContrast = Color(0xFFCC7B74)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF141218)
val onBackgroundDarkMediumContrast = Color(0xFFE6E0E9)
val surfaceDarkMediumContrast = Color(0xFF141218)
val onSurfaceDarkMediumContrast = Color(0xFFFFF9FF)
val surfaceVariantDarkMediumContrast = Color(0xFF49454E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFCEC8D4)
val outlineDarkMediumContrast = Color(0xFFA6A1AB)
val outlineVariantDarkMediumContrast = Color(0xFF86818B)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE6E0E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B292F)
val inversePrimaryDarkMediumContrast = Color(0xFF4E3F77)
val surfaceDimDarkMediumContrast = Color(0xFF141218)
val surfaceBrightDarkMediumContrast = Color(0xFF3B383E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0F0D13)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1B20)
val surfaceContainerDarkMediumContrast = Color(0xFF211F24)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2B292F)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF36343A)

val primaryDarkHighContrast = Color(0xFFFFF9FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD3C1FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFD3C1FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9F9)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFB7CD)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFB9B3)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF141218)
val onBackgroundDarkHighContrast = Color(0xFFE6E0E9)
val surfaceDarkHighContrast = Color(0xFF141218)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49454E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9FF)
val outlineDarkHighContrast = Color(0xFFCEC8D4)
val outlineVariantDarkHighContrast = Color(0xFFCEC8D4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE6E0E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2F2056)
val surfaceDimDarkHighContrast = Color(0xFF141218)
val surfaceBrightDarkHighContrast = Color(0xFF3B383E)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0F0D13)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D1B20)
val surfaceContainerDarkHighContrast = Color(0xFF211F24)
val surfaceContainerHighDarkHighContrast = Color(0xFF2B292F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF36343A)







